# Generated by Django 4.2.5 on 2024-04-13 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='', max_length=80, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre_usuario',
            field=models.CharField(max_length=100, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.roluser'),
            preserve_default=False,
        ),
    ]
