# Generated by Django 4.2.5 on 2024-04-13 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('categoria_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Rol')),
                ('rol_nombre', models.CharField(max_length=50, verbose_name='Nombre Rol')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('contrasena', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.roluser')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('juego_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Juego')),
                ('juego_nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='juegos/')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
