# Generated by Django 4.2.5 on 2024-04-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
